SELECT LARGEORDERS.orderkey, 
       LARGEORDERS.orderdate,
       LARGEORDERS.shippriority,
       extendedprice * (1 - discount) AS query3
FROM   LARGECUSTOMER, LARGEORDERS, LARGELINEITEM
WHERE  LARGECUSTOMER.mktsegment = 'BUILDING'
  AND  LARGEORDERS.custkey = LARGECUSTOMER.custkey
  AND  LARGELINEITEM.orderkey = LARGEORDERS.orderkey
  AND  LARGEORDERS.orderdate < TO_DATE('1995-03-15', 'YYYY-MM-DD')
  AND  LARGELINEITEM.shipdate > TO_DATE('1995-03-15', 'YYYY-MM-DD');