SELECT XLARGEORDERS.orderkey, 
       XLARGEORDERS.orderdate,
       XLARGEORDERS.shippriority,
       extendedprice * (1 - discount) AS query3
FROM   XLARGECUSTOMER, XLARGEORDERS, XLARGELINEITEM
WHERE  XLARGECUSTOMER.mktsegment = 'BUILDING'
  AND  XLARGEORDERS.custkey = XLARGECUSTOMER.custkey
  AND  XLARGELINEITEM.orderkey = XLARGEORDERS.orderkey
  AND  XLARGEORDERS.orderdate < TO_DATE('1995-03-15', 'YYYY-MM-DD')
  AND  XLARGELINEITEM.shipdate > TO_DATE('1995-03-15', 'YYYY-MM-DD');