CREATE LENS XSUPPLIER AS SELECT * FROM SUPPLIER WITH MISSING_VALUE('NATIONKEY');
CREATE LENS XPARTSUPP AS SELECT * FROM PARTSUPP WITH MISSING_VALUE('PARTKEY', 'SUPPKEY');
CREATE LENS XCUSTOMER AS SELECT * FROM CUSTOMER WITH MISSING_VALUE('NATIONKEY');
CREATE LENS XLINEITEM AS SELECT * FROM LINEITEM WITH MISSING_VALUE('ORDERKEY', 'PARTKEY', 'SUPPKEY');
CREATE LENS XORDERS AS SELECT * FROM ORDERS WITH MISSING_VALUE('CUSTKEY');
CREATE LENS XNATION AS SELECT * FROM NATION WITH MISSING_VALUE('REGIONKEY');
